### ISSUE TITLE
[Bug]: the logout menu seems broken after I changed my monitor scaling to 1.25

### ISSUE THREAD

**Issue by experience4678** [JaKooLit/Hyprland-Dots#572]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```
<Paste the output of the command here, without removing any formatting around this>
```

</details>

### KooL's Dots version

Latest

### Description

Pls see the image uploaded thankyou.

### How to reproduce

.

### install logs, images or videos

![Image](https://github.com/user-attachments/assets/c838b9bd-4922-4f01-bf07-221f969e0941)

**Comment by JaKooLit** [comment]
can you attach here you ~/.config/hypr/scripts/Wlogout.sh

and also, kindly state resolution

**Comment by experience4678** [comment]
#!/bin/bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ ##
# wlogout (Power, Screen Lock, Suspend, etc)

# Parameters for screen resolutions
declare -A resolutions=(
    [2160]=450
    [1600]=450
    [1440]=450
    [1080]=350
    [720]=175
)

# Check if wlogout is already running, if so, kill it
if pgrep -x "wlogout" > /dev/null; then
    pkill -x "wlogout"
    exit 0
fi

# Detect the current monitor's native resolution and scale
monitor_info=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true)')
# extract some info
resolution=$(echo "$monitor_info" | jq -r '.height')
width=$(echo "$monitor_info" | jq -r '.width')
hypr_scale=$(echo "$monitor_info" | jq -r '.scale')

# If hypr_scale >= 1.25 or resolution can't be detected, run wlogout with -b 3 
if [[ -z "$resolution" || ! "$resolution" =~ ^[0-9]+$ || -z "$hypr_scale" || $(awk "BEGIN {exit !($hypr_scale >= 1.25)}") -eq 1 ]]; then
    echo "Hypr_scale is greater than or equal to 1.25 or resolution could not be detected, running wlogout with -b 3"
    wlogout --protocol layer-shell -b 3 -T 100 -B 100 &
    exit 0
fi

# Determine the appropriate resolution range and calculate T and B values
if ((resolution >= 2160)); then
    res_key=2160
elif ((resolution >= 1600)); then
    res_key=1600
elif ((resolution >= 1440)); then
    res_key=1440
elif ((resolution >= 1080)); then
    res_key=1080
else
    res_key=720
fi

# Calculate T and B values based on selected resolution and scale
T_val=$(awk "BEGIN {printf \"%.0f\", ${resolutions[$res_key]} * $res_key * $hypr_scale / $resolution}")
B_val=$(awk "BEGIN {printf \"%.0f\", ${resolutions[$res_key]} * $res_key * $hypr_scale / $resolution}")

# Output the resolution setting for debugging purposes
echo "Setting parameters for resolution >= $res_key"

# Run wlogout with -b 6 and calculated T/B values
wlogout --protocol layer-shell -b 6 -T $T_val -B $B_val &


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
my resolution is 1920*1080 (1080p full hd), thankyou jk

**Comment by experience4678** [comment]
[cba2d37d58ce1f8a2f8bc896ad42d810_forcedtxt_from_sh.pdf](https://github.com/user-attachments/files/18887337/cba2d37d58ce1f8a2f8bc896ad42d810_forcedtxt_from_sh.pdf)

sorry .sh file was not allowed to upload, so i have uploaded pdf and my screen resolution is 1920*1080 (1080p)

**Comment by experience4678** [comment]
```
#!/bin/bash
# /* ---- ? https://github.com/JaKooLit ? ---- */ ##
# wlogout (Power, Screen
Lock, Suspend, etc)
# Parameters for screen resolutions
declare -A resolutions=(
[2160]=450
[1600]=450
[1440]=450
[1080]=350
[720]=175
)
# Check if wlogout is
already running, if so, kill it
if pgrep -x "wlogout" > /dev/null; then
pkill
-x "wlogout"
exit 0
fi
# Detect the current monitor's native resolution and
scale
monitor_info=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true)')
#
extract some info
resolution=$(echo "$monitor_info" | jq -r
'.height')
width=$(echo "$monitor_info" | jq -r
'.width')
hypr_scale=$(echo "$monitor_info" | jq -r '.scale')
#
If hypr_scale >= 1.25 or resolution can't be detected, run wlogout with -b 3
if [[ -z
"$resolution" || ! "$resolution" =~ ^[0-9]+$ || -z "$hypr_scale"
|| $(awk "BEGIN {exit !($hypr_scale >= 1.25)}") -eq 1 ]]; then
echo
"Hypr_scale is greater than or equal to 1.25 or resolution could not be detected, running
wlogout with -b 3"
wlogout --protocol layer-shell -b 3 -T 100 -B 100 &
exit
0
fi
# Determine the appropriate resolution range and calculate T and B values
if ((resolution
>= 2160)); then
res_key=2160
elif ((resolution >= 1600)); then
res_key=1600
elif
((resolution >= 1440)); then
res_key=1440
elif ((resolution >= 1080)); then
res_key=1080
else
res_key=720
fi
# Calculate T and B values based on selected resolution
and scale
T_val=$(awk "BEGIN {printf \"%.0f\", ${resolutions[$res_key]} *
$res_key * $hypr_scale / $resolution}")
B_val=$(awk "BEGIN {printf
\"%.0f\", ${resolutions[$res_key]} * $res_key * $hypr_scale / $resolution}")
#
Output the resolution setting for debugging purposes
echo "Setting parameters for
resolution >= $res_key"
# Run wlogout with -b 6 and calculated T/B values
wlogout
--protocol layer-shell -b 6 -T $T_val -B $B_val &
```

**Comment by JaKooLit** [comment]
its ok thanks

you can actually attach as code so its easier to read

anyway, ive a push a fix 

https://github.com/JaKooLit/Hyprland-Dots/commit/9f5b41c3e230cda406592167fcd0446a5f56821c

can you try?

**Comment by experience4678** [comment]
```
#!/bin/bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ ##
# wlogout (Power, Screen Lock, Suspend, etc)

# Parameters for screen resolutions
declare -A resolutions=(
    [2160]=450
    [1600]=450
    [1440]=450
    [1080]=350
    [720]=175
)

# Check if wlogout is already running, if so, kill it
if pgrep -x "wlogout" > /dev/null; then
    pkill -x "wlogout"
    exit 0
fi

# Detect the current monitor's native resolution and scale
monitor_info=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true)')
# extract some info
resolution=$(echo "$monitor_info" | jq -r '.height')
width=$(echo "$monitor_info" | jq -r '.width')
hypr_scale=$(echo "$monitor_info" | jq -r '.scale')

# If hypr_scale >= 1.25 or resolution can't be detected, run wlogout with -b 3 
if [[ -z "$resolution" || ! "$resolution" =~ ^[0-9]+$ || -z "$hypr_scale" || $(awk "BEGIN {exit !($hypr_scale >= 1.25)}") -eq 1 ]]; then
    echo "Hypr_scale is greater than or equal to 1.25 or resolution could not be detected, running wlogout with -b 3"
    wlogout --protocol layer-shell -b 3 -T 100 -B 100 &
    exit 0
fi

# Determine the appropriate resolution range and calculate T and B values
if ((resolution >= 2160)); then
    res_key=2160
elif ((resolution >= 1600)); then
    res_key=1600
elif ((resolution >= 1440)); then
    res_key=1440
elif ((resolution >= 1080)); then
    res_key=1080
else
    res_key=720
fi

# Calculate T and B values based on selected resolution and scale
T_val=$(awk "BEGIN {printf \"%.0f\", ${resolutions[$res_key]} * $res_key * $hypr_scale / $resolution}")
B_val=$(awk "BEGIN {printf \"%.0f\", ${resolutions[$res_key]} * $res_key * $hypr_scale / $resolution}")

# Output the resolution setting for debugging purposes
echo "Setting parameters for resolution >= $res_key"

# Run wlogout with -b 6 and calculated T/B values
wlogout --protocol layer-shell -b 6 -T $T_val -B $B_val &
``` 

is that ok

**Comment by JaKooLit** [comment]
This is fixed?

**Comment by experience4678** [comment]
No this is not the fixed one , sorry I am noob I can't figure out that whether I have to paste the updated wlogout.sh given by you in my existing wlogout.sh or you will update the dotfiles to fix it, sorry for the inconvenience.

**Comment by skarpinis** [comment]
> https://github.com/JaKooLit/Hyprland-Dots/blob/main/config%2Fhypr%2Fscripts%2FWlogout.sh
> 
> copy contents of this and replace that file

Hi, on 4k with 1.5 scale still not right, everything is why too big

**Comment by JaKooLit** [comment]
I set it like that

anything scaling above 1.25 it will be big

when not on scale, then it will be horizontally

**Comment by skarpinis** [comment]
ok nevermind my solution: :)
A_2160=700
B_2160=700
A_1600=650
B_1600=650
A_1440=350
B_1440=350
A_1080=350
B_1080=350
A_720=50
B_720=50

**Comment by experience4678** [comment]
Will try it thanks

**Comment by skarpinis** [comment]
> I set it like that
> 
> anything scaling above 1.25 it will be big
> 
> when not on scale, then it will be horizontally

just tested with 1.0 and 1.25 scale on 4k screen still broken

![Image](https://github.com/user-attachments/assets/d8e19f9b-895b-4ea4-b2be-4c3d61992cfc)

**Comment by JaKooLit** [comment]
Thats the reason why I set that anything scaling from 1.25, it will default to "BIG"

![Image](https://github.com/user-attachments/assets/4465d340-9cb4-488b-b4b4-9c816a5d8255)

**Comment by JaKooLit** [comment]
cant find a good balance lmao

**Comment by skarpinis** [comment]
> cant find a good balance lmao

and 1 scale still very long :(

![Image](https://github.com/user-attachments/assets/09fad469-c3ed-423c-a9fa-007d4024c76c)

**Comment by skarpinis** [comment]
fixed for 4k 1.75 and 300 monitor scale 1.5 :)
